---
- name: My first playbook :)
  hosts: "webservers"
  become: true
  become_user: root
  roles:
    - { role: apache }
    
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'

    - { role: mysql }
    
    - { role: mpfcopy }